### ISSUE TITLE
support allowInsecureRegistries

### ISSUE THREAD

**Issue by gnarroway** [atomisthq/jibbit#9]
gradle/maven jib have a flag to `allowInsecureRegistries` which is useful in certain environments. 

Can jibbit be made to support a similar config?

**Comment by slimslenderslacks** [comment]
@gnarroway ya, I can add this flag - this is exposed on the underlying Containerizer so I'll add an option for that.

**Comment by gnarroway** [comment]
Thank you.

_<edited to move to a new issue>_

**Comment by slimslenderslacks** [comment]
@gnarroway I named the flag `:allow-insecure-registries` just to stick with the clojure convention.  I've started to add some tests for container contents but I haven't got around to setting up a registry with a self-signed certificate to test whether this is working yet.  When you need to push to an insecure registry, is it because you're pushing to something using a self-signed certificate?

You should be able to try this flag now:  https://github.com/atomisthq/jibbit#pushing-to-insecure-registries
